// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IRiscZeroVerifier
/// @notice Interface for a RISC Zero proof verifier.
/// @dev In production, deploy Risc0's official RiscZeroGroth16Verifier contract and pass its
///      address to the PrivateVoting constructor.  For local testing, deploy MockVerifier.sol.
///      See: https://github.com/risc0/risc0-ethereum
interface IRiscZeroVerifier {
    /// @notice Verify a RISC Zero proof.
    /// @param seal        The proof (Groth16 seal bytes from the prover).
    /// @param imageId     The circuit image ID (computed deterministically from the ELF binary).
    /// @param journalDigest SHA-256 digest of the public journal (committed outputs).
    /// @return True if the proof is valid, false otherwise.
    function verify(
        bytes calldata seal,
        bytes32 imageId,
        bytes32 journalDigest
    ) external view returns (bool);
}

/// @title PrivateVoting
/// @notice On-chain vote tallying contract that enforces ZK proof validity.
///
/// Each vote must be accompanied by a valid RISC Zero ZK proof generated by the vote circuit.
/// The proof attests that:
///   - The vote choice (0 = No, 1 = Yes) is binary.
///   - The nullifier is correctly derived as SHA-256("nullifier-v1" || voter_id || secret).
///
/// Journal layout (64 bytes, matching zk-circuits/methods/guest/src/bin/vote.rs):
///   bytes  0..32: voteHash   — 32-byte word; last byte = vote_choice, rest zeroed.
///   bytes 32..64: nullifier  — SHA-256(voter identity commitment).
///
/// NOTE: Merkle-based voter eligibility verification is not yet implemented.
///       The merkleRoot field is reserved for a future upgrade that will require
///       each voter to prove membership in an eligible-voter set.
contract PrivateVoting {
    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    /// Merkle root of the eligible voter set (reserved for future eligibility checks).
    bytes32 public merkleRoot;

    /// RISC Zero image ID for the vote circuit ELF binary.
    bytes32 public imageId;

    /// On-chain proof verifier (IRiscZeroVerifier implementation).
    IRiscZeroVerifier public verifier;

    /// Nullifiers that have already been used, keyed by their uint256 representation.
    /// Prevents double-voting: each (voter_id, secret) pair produces a unique nullifier.
    mapping(bytes32 => bool) public nullifiers;

    /// Vote counts: proposalId => voteChoice (0/1) => count.
    mapping(uint256 => mapping(uint256 => uint256)) public voteCounts;

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------

    event VoteCast(uint256 indexed proposalId, uint256 voteChoice, bytes32 nullifier);

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /// @param _merkleRoot Eligible voter Merkle root (reserved for future use).
    /// @param _imageId    RISC Zero image ID of the vote circuit.
    /// @param _verifier   Address of the IRiscZeroVerifier implementation.
    ///                    Use MockVerifier for testing, RiscZeroGroth16Verifier for production.
    constructor(bytes32 _merkleRoot, bytes32 _imageId, address _verifier) {
        merkleRoot = _merkleRoot;
        imageId = _imageId;
        verifier = IRiscZeroVerifier(_verifier);
    }

    // -----------------------------------------------------------------------
    // Voting
    // -----------------------------------------------------------------------

    /// @notice Cast a private vote backed by a RISC Zero ZK proof.
    /// @param journal Raw journal bytes committed by the ZK circuit (64 bytes).
    ///                Layout: [voteHash: bytes32][nullifier: bytes32]
    /// @param seal    Proof seal (Groth16 bytes from the RISC Zero prover).
    ///                For production use RISC0's Groth16 prover; for demos use MockVerifier.
    function castVote(bytes calldata journal, bytes calldata seal) external {
        require(journal.length == 64, "Invalid journal length: expected 64 bytes");

        // 1. Verify the ZK proof.
        //    sha256(journal) is the journal digest the proof commits to.
        bytes32 journalDigest = sha256(journal);
        require(
            verifier.verify(seal, imageId, journalDigest),
            "Invalid ZK proof"
        );

        // 2. Decode journal — layout matches zk-circuits/methods/guest/src/bin/vote.rs.
        //    voteHash:  bytes32 — last byte is vote_choice (0 or 1), rest zeroed.
        //    nullifier: bytes32 — SHA-256("nullifier-v1" || voter_id || secret).
        (bytes32 voteHash, bytes32 nullifier) = abi.decode(journal, (bytes32, bytes32));

        // 3. Extract vote choice from the last byte of voteHash.
        uint256 voteChoice = uint256(voteHash) & 0xFF;
        require(voteChoice <= 1, "Invalid vote choice in journal");

        // 4. Enforce nullifier uniqueness (prevents double-voting).
        require(!nullifiers[nullifier], "Double voting detected");
        nullifiers[nullifier] = true;

        // 5. Record the vote (proposalId = 0 for this demo; extend journal to support multiple proposals).
        uint256 proposalId = 0;
        voteCounts[proposalId][voteChoice]++;

        emit VoteCast(proposalId, voteChoice, nullifier);
    }
}
